"""
Django settings for Group10 project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import base64 # for encoding the API key
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()  # load from .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from web3 import Web3

TEST_RUNNER = "core.test_runner.MyTestRunner"

#change in production
#Ganache,remix,MetaMask details
GANACHE_URL = os.getenv('GANACHE_URL')

GANACHE_PRIVATE_KEY = os.getenv('GANACHE_PRIVATE_KEY')  #ganache account 2 private key
COMPANY_MAIN_WALLET = Web3.to_checksum_address("0x381340d14a8d304FFaD95970636E046a61236396") #ganache account 2
# PAYMENT_CONTRACT_ADDRESS = "0x8b564427D5F1AA731E51FcE3637cE291D284cfc8"
PAYMENT_CONTRACT_ADDRESS="0x495b93504F0Aa82b3AD3B9A7A525719E1E72Af29" #ganache remix deployment
SHIPMENT_CONTRACT_ADDRESS = "0x2D91eB47966bAeB060D6C9DBAb1470e8D489F682" #ganache remix deployment
TRACKING_CONTRACT_ADDRESS = "0x82DC8D261E7C4009bB22f25f07c9c8bfFEc6F08b" #ganache remix deployment

# ABIs - load from local folders
TRACKING_CONTRACT_ABI="blockchain/abi/TrackingContractABI.json"


PAYMENT_CONTRACT_ABI =[
	{
		"inputs": [
			{
				"components": [
					{
						"internalType": "string",
						"name": "quote_request_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "transaction_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "payment_type",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "amount_purpose",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "blockchain_gas_amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "source_wallet",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "status",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "created_at",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "created_by",
						"type": "string"
					},
					{
						"internalType": "bool",
						"name": "payment_email_sent",
						"type": "bool"
					},
					{
						"internalType": "string",
						"name": "user_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "transaction_hash",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "confirmed_at",
						"type": "uint256"
					}
				],
				"internalType": "struct Payment.PaymentRecord",
				"name": "_payment",
				"type": "tuple"
			}
		],
		"name": "createPayment",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "_transaction_id",
				"type": "string"
			}
		],
		"name": "markEmailSent",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_destination",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "string",
				"name": "transaction_id",
				"type": "string"
			}
		],
		"name": "EmailMarkedSent",
		"type": "event"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "address",
				"name": "previousOwner",
				"type": "address"
			},
			{
				"indexed": True,
				"internalType": "address",
				"name": "newOwner",
				"type": "address"
			}
		],
		"name": "OwnershipTransferred",
		"type": "event"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "string",
				"name": "transaction_id",
				"type": "string"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "string",
				"name": "status",
				"type": "string"
			}
		],
		"name": "PaymentCreated",
		"type": "event"
	},
	{
		"inputs": [],
		"name": "renounceOwnership",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "newOwner",
				"type": "address"
			}
		],
		"name": "transferOwnership",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "withdraw",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "destination",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "_transaction_id",
				"type": "string"
			}
		],
		"name": "getPayment",
		"outputs": [
			{
				"components": [
					{
						"internalType": "string",
						"name": "quote_request_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "transaction_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "payment_type",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "amount_purpose",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "blockchain_gas_amount",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "source_wallet",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "status",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "created_at",
						"type": "uint256"
					},
					{
						"internalType": "string",
						"name": "created_by",
						"type": "string"
					},
					{
						"internalType": "bool",
						"name": "payment_email_sent",
						"type": "bool"
					},
					{
						"internalType": "string",
						"name": "user_id",
						"type": "string"
					},
					{
						"internalType": "string",
						"name": "transaction_hash",
						"type": "string"
					},
					{
						"internalType": "uint256",
						"name": "confirmed_at",
						"type": "uint256"
					}
				],
				"internalType": "struct Payment.PaymentRecord",
				"name": "",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "owner",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "string",
				"name": "_transaction_id",
				"type": "string"
			}
		],
		"name": "paymentExists",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]



# setting Email account details
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')

# Session will expire after 15 minutes of inactivity
SESSION_COOKIE_AGE = 15 * 60   # 15 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True

# Point Django to your actual login page
LOGIN_URL = '/apps/Login/'      # <-- adjust this to match your login route
LOGOUT_REDIRECT_URL = '/apps/Login/'  # where to go after logout

#change in production
#APP URL
APP_URL=os.getenv('APP_URL')

LOCATIONIQ_API_KEY = "pk.804861130e8f781629bf632d76f18f54"  # Replace with your LocationIQ key
# 🔐 Encrypt the key before sending to the client
def encrypt_key(api_key: str) -> str:
    return base64.b64encode(api_key.encode()).decode()
API_KEY = encrypt_key(LOCATIONIQ_API_KEY)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ntt^$7g6@gt&6-88+co)=20jhu+e9@2t(y5dx!4!0b!m2vz$p='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ngrok url for testing webhook in development
CSRF_TRUSTED_ORIGINS = [
    "https://40ae-149-115-35-106.ngrok-free.app"
]
#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

# Default apps provided by Django
DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions', # added for checking: python manage.py show_urls

]

THIRD_PARTY_APPS = [
    # add apps which you install using pip
]

LOCAL_APPS = [
    # add local apps which you create using startapp
    'apps.Login',
    'apps.Home',
    'apps.Quotings',
    'apps.Documentations',
    'apps.Bookings',
    'apps.Payments',
    'apps.Shipments',
    'apps.Products',
    'apps.Reports',
    'apps.Account_settings',
]

# Application definition
INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.Helpers.auto_logout.AutoLogoutMiddleware', # logout user of inactive session
]


ROOT_URLCONF = 'Jenik_freight_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.Helpers.context_processors.onboarding_status', # Custom context processor to check onboarding status for clients and display it in 
                'apps.Helpers.context_processors.locationiq_key', # Custom context processor to provide LocationIQ API key
            ],
        },
    },
]

WSGI_APPLICATION = 'Jenik_freight_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Canada/Mountain"   # or "America/Edmonton"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Loading from local_settings.py file
try:
    from Jenik_freight_crm.local_settings import *
except ImportError:
    pass