# Generated by Django 5.2.4 on 2025-10-08 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='credit_application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField(auto_now=True)),
                ('legal_trading_name', models.CharField(max_length=100)),
                ('operating_as', models.CharField(default='N/a', max_length=100)),
                ('business_location', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('length_in_business', models.CharField(default='Less than 1 Year', max_length=30)),
                ('type_of_business', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_address', models.CharField(max_length=200)),
                ('bank_fax', models.CharField(default='N/a', max_length=30)),
                ('importer', models.CharField(default='N/a', max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_app_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_application',
            },
        ),
        migrations.CreateModel(
            name='address_of_owner_officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField(auto_now=True)),
                ('owner_name', models.CharField(default='N/a', max_length=50)),
                ('owner_title', models.CharField(max_length=50)),
                ('owner_address', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=30)),
                ('id_reference_cred_app_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_address_owner_credit_app_table', to='Documentations.credit_application')),
            ],
            options={
                'db_table': 'address_of_owner_officer',
            },
        ),
        migrations.CreateModel(
            name='credit_references',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField(auto_now=True)),
                ('referee_name', models.CharField(max_length=30)),
                ('referee_address', models.CharField(max_length=200)),
                ('referee_phone', models.CharField(max_length=30)),
                ('id_reference_cred_app_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reference_credit_app_table', to='Documentations.credit_application')),
            ],
            options={
                'db_table': 'credit_references',
            },
        ),
    ]
