# Generated by Django 5.2.4 on 2025-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_payment_net_amount_payment_stripe_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fx_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
