# Generated by Django 5.2.4 on 2025-10-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_payment_fx_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
