# Generated by Django 5.2.4 on 2025-10-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_payment_settled_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
