# Generated by Django 5.2.4 on 2025-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_payment_payment_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
