# Generated by Django 5.2.4 on 2025-10-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0007_payment_email_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_card_status',
            field=models.CharField(default='Card not Charged', max_length=25),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_availability',
            field=models.CharField(default='Unavailable', max_length=15),
        ),
    ]
