# Generated by Django 5.2.4 on 2026-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0008_payment_customer_card_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockchain_payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('quote_request_id', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blockchain_payment',
            },
        ),
    ]
