# Generated by Django 5.2.4 on 2026-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0009_blockchain_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain_payment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='blockchain_payment',
            name='blockchain_gas_fees',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='blockchain_payment',
            name='date_created',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
