# Generated by Django 5.2.4 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0010_blockchain_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain_payment',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='blockchain_payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='blockchain_payment',
            name='total_charges',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
