# Generated by Django 5.2.4 on 2025-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_quotings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.CharField(max_length=35)),
                ('time_received', models.CharField(max_length=35)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, default='Guest', unique=True)),
                ('shipper_company_name', models.CharField(max_length=100, default='No Company')),
                ('shipper_fullname', models.CharField(max_length=100, default='Guest')),
                ('shipper_phone_number', models.CharField(max_length=50)),
                ('shipper_email', models.EmailField(max_length=254)),
                ('shipper_export_number', models.CharField(max_length=50, default='No Export Number')),
                ('shipper_address', models.CharField(max_length=255)),
                ('receiver_company_name', models.CharField(max_length=100, default='No Company')),
                ('receiver_fullname', models.CharField(max_length=100, default='Guest')),
                ('receiver_phone_number', models.CharField(max_length=50)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_tax_id', models.CharField(max_length=50, default='N/A')),
                ('receiver_driver_lincence', models.CharField(max_length=50, default='N/A')),
                ('receiver_passport_no', models.CharField(max_length=50, default='N/A')),
                ('receiver_address', models.CharField(max_length=255)),
                ('shipment_date', models.CharField(max_length=35)),
                ('shipment_type', models.CharField(max_length=50)),
                ('shipment_weight', models.DecimalField(max_digits=10, decimal_places=2)),
                ('shipment_dimensions', models.CharField(max_length=100)),
                ('resolution_code', models.CharField(max_length=35, default='Open')),
                ('resolution_date', models.DateField(null=True, blank=True)),
                ('resolution_time', models.TimeField(null=True, blank=True)),
                ('convert_to_booking', models.CharField(max_length=7, default='False')),
                ('message', models.TextField(max_length=300)),
                ('locked_by', models.CharField(max_length=50, default='0')),
            ],
            options={
                'db_table': 'new_quotings',
            },
        ),
    ]
