# Generated by Django 5.2.4 on 2025-08-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_quotings',
            name='receiver_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new_quotings',
            name='receiver_fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new_quotings',
            name='shipper_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='sea_additional_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_of_receipt', models.CharField(default='N/A', max_length=255)),
                ('port_of_loading', models.CharField(default='N/A', max_length=255)),
                ('seal_number', models.CharField(default='N/A', max_length=100)),
                ('container_number', models.CharField(default='N/A', max_length=100)),
                ('vessel_number', models.CharField(default='N/A', max_length=100)),
                ('port_of_discharge', models.CharField(default='N/A', max_length=255)),
                ('cargo_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desired_type_of_release', models.CharField(default='N/A', max_length=50)),
                ('hs_code', models.CharField(default='N/A', max_length=50)),
                ('cers', models.CharField(default='N/A', max_length=50)),
                ('booking_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_info_by_request_id', to='Login.new_quotings', to_field='request_id')),
                ('id_quoting_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_info_by_id', to='Login.new_quotings')),
            ],
            options={
                'db_table': 'sea_additional_info',
            },
        ),
    ]
