# Generated by Django 5.2.4 on 2025-08-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_new_quotings_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sea_additional_info',
            name='booking_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sea_info_by_request_id', to='Login.new_quotings', to_field='request_id'),
        ),
        migrations.AlterField(
            model_name='sea_additional_info',
            name='id_quoting_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sea_info_by_id', to='Login.new_quotings'),
        ),
    ]
