# Generated by Django 5.2.4 on 2025-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_sea_additional_info_booking_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_quotings',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
