# Generated by Django 5.2.4 on 2025-08-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_new_quotings_receiver_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sea_additional_info',
        ),
    ]
