# Generated by Django 5.2.4 on 2025-08-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_delete_sea_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quoting_id', models.CharField(max_length=35)),
                ('booking_ref', models.CharField(max_length=35)),
                ('goods_quantity', models.IntegerField(default=1)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quoting_id', models.CharField(max_length=35)),
                ('booking_ref', models.CharField(max_length=35)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_vin', models.CharField(max_length=100, unique=True)),
                ('vehicle_cost', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='sea_additional_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(max_length=255)),
                ('place_of_receipt', models.CharField(default='N/A', max_length=255)),
                ('port_of_loading', models.CharField(default='N/A', max_length=255)),
                ('seal_number', models.CharField(default='N/A', max_length=100)),
                ('container_number', models.CharField(default='N/A', max_length=100)),
                ('vessel_number', models.CharField(default='N/A', max_length=100)),
                ('port_of_discharge', models.CharField(default='N/A', max_length=255)),
                ('cargo_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desired_type_of_release', models.CharField(default='N/A', max_length=50)),
                ('hs_code', models.CharField(default='N/A', max_length=50)),
                ('cers', models.CharField(default='N/A', max_length=50)),
                ('id_quoting_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_info_by_id', to='Login.new_quotings')),
            ],
            options={
                'db_table': 'sea_additional_info',
            },
        ),
    ]
