# Generated by Django 5.2.4 on 2025-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_goods_vehicle_sea_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_quotings',
            name='username',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
