# Generated by Django 5.2.4 on 2025-08-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_new_quotings_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='onboarding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_signed', models.CharField(max_length=35)),
                ('time_signed', models.CharField(max_length=35)),
                ('username', models.CharField(default='default_username', max_length=35, unique=True)),
                ('GSA_signed', models.CharField(default='No', max_length=4)),
                ('LOI_signed', models.CharField(default='No', max_length=4)),
                ('credits_application_signed', models.CharField(default='No', max_length=4)),
            ],
            options={
                'db_table': 'onboarding',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='quoting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_quoting_id', to='Login.new_quotings'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='quoting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoting_id', to='Login.new_quotings'),
        ),
    ]
