# Generated by Django 5.2.4 on 2025-08-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_onboarding_alter_goods_quoting_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='GSA_signed',
            new_name='gsa_signed',
        ),
        migrations.RenameField(
            model_name='onboarding',
            old_name='LOI_signed',
            new_name='loi_signed',
        ),
    ]
