# Generated by Django 5.2.4 on 2025-08-17 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_rename_gsa_signed_onboarding_gsa_signed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSA_agreement_form_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('username', models.CharField(editable=False, max_length=100)),
                ('customer_registered_business_name', models.CharField(default='N/A', max_length=100)),
                ('corp_jur_number', models.CharField(max_length=50)),
                ('service_address', models.TextField(max_length=300)),
                ('billing_address', models.CharField(max_length=100)),
                ('GST_HST', models.CharField(max_length=100)),
                ('business_form', models.CharField(max_length=50)),
                ('auth_contact_number', models.CharField(max_length=50)),
                ('telephone_number', models.CharField(max_length=100)),
                ('fax_number', models.CharField(default='N/A', max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('bank_name', models.CharField(default='N/A', max_length=100)),
                ('branch_id', models.CharField(default='N/A', max_length=100)),
                ('bank_address', models.CharField(default='N/A', max_length=100)),
                ('bank_account_number', models.CharField(default='N/A', max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('locked_by', models.CharField(default='0', max_length=50)),
                ('user_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GSA_agreement_form_tbl',
            },
        ),
    ]
