# Generated by Django 5.2.4 on 2025-08-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_gsa_agreement_form_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsa_agreement_form_tbl',
            name='bank_address',
            field=models.TextField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='gsa_agreement_form_tbl',
            name='billing_address',
            field=models.TextField(max_length=300),
        ),
    ]
