# Generated by Django 5.2.4 on 2025-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_alter_gsa_agreement_form_tbl_bank_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsa_agreement_form_tbl',
            name='username',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
