# Generated by Django 5.2.4 on 2025-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_air_freight_tbl_customs_brokerage_tbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_freight_tbl',
            name='units_of_measurement',
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='unit_of_measurement_L_W_H',
            field=models.CharField(default='Centimeters', max_length=15),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='unit_of_measurement_weight',
            field=models.CharField(default='Kgs', max_length=10),
        ),
    ]
