# Generated by Django 5.2.4 on 2025-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_remove_air_freight_tbl_units_of_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roro_tbl',
            name='units_of_measurement',
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='unit_of_measurement_L_W_H',
            field=models.CharField(default='Centimeters', max_length=15),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='unit_of_measurement_weight',
            field=models.CharField(default='Kgs', max_length=10),
        ),
    ]
