# Generated by Django 5.2.4 on 2025-08-29 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_remove_roro_tbl_units_of_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customs_brokerage_tbl',
            name='invoice_packing_list_upload',
        ),
        migrations.CreateModel(
            name='CustomsBrokerageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customs_brokerage/%Y/%m/%d/')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Login.customs_brokerage_tbl')),
            ],
            options={
                'db_table': 'CustomsBrokerageFile',
            },
        ),
    ]
