# Generated by Django 5.2.4 on 2025-08-29 23:01

import apps.Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_remove_customs_brokerage_tbl_invoice_packing_list_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsbrokeragefile',
            name='file',
            field=models.FileField(upload_to=apps.Login.models.upload_to_request),
        ),
    ]
