# Generated by Django 5.2.4 on 2025-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0017_alter_customsbrokeragefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_freight_tbl',
            name='commodity_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='commodity_sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='commodity_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='commodity_sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='commodity_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='commodity_sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='commodity_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='commodity_sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
