# Generated by Django 5.2.4 on 2025-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0018_air_freight_tbl_commodity_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_freight_tbl',
            name='from_airpot_address',
        ),
        migrations.RemoveField(
            model_name='air_freight_tbl',
            name='to_airport_address',
        ),
        migrations.RemoveField(
            model_name='customs_brokerage_tbl',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='customs_brokerage_tbl',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='ocean_freight_tbl',
            name='shipping_destination_address',
        ),
        migrations.RemoveField(
            model_name='ocean_freight_tbl',
            name='shipping_origin_address',
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='country_of_depature',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='country_of_destination',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='departure',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='destination',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='place_of_receipt',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='country_of_discharge',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='country_of_loading',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='place_of_receipt',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='port_of_discharge',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='port_of_loading',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='country_of_discharge',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='country_of_loading',
            field=models.TextField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='place_of_receipt',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='port_of_discharge',
            field=models.TextField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='port_of_loading',
            field=models.TextField(default='Unknown', max_length=300),
        ),
    ]
