# Generated by Django 5.2.4 on 2025-09-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_remove_air_freight_tbl_from_airpot_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_freight_tbl',
            old_name='country_of_depature',
            new_name='country_of_departure',
        ),
    ]
