# Generated by Django 5.2.4 on 2025-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0020_rename_country_of_depature_air_freight_tbl_country_of_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_freight_tbl',
            name='door_delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='door_delivery_service',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='door_delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='door_delivery_service',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='door_delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='door_delivery_service',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='door_delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='door_delivery_service',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
