# Generated by Django 5.2.4 on 2025-09-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0021_air_freight_tbl_door_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_freight_tbl',
            name='door_delivery_address',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='door_delivery_address',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='door_delivery_address',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='door_delivery_address',
            field=models.CharField(default='N/A', max_length=5),
        ),
    ]
