# Generated by Django 5.2.4 on 2025-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0023_alter_air_freight_tbl_door_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_freight_tbl',
            old_name='door_delivery_service',
            new_name='hazardous',
        ),
        migrations.RenameField(
            model_name='customs_brokerage_tbl',
            old_name='door_delivery_service',
            new_name='hazardous',
        ),
        migrations.RenameField(
            model_name='ocean_freight_tbl',
            old_name='door_delivery_service',
            new_name='hazardous',
        ),
        migrations.RenameField(
            model_name='roro_tbl',
            old_name='door_delivery_service',
            new_name='hazardous',
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='service_type',
            field=models.CharField(default='Ramp', max_length=10),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='service_type',
            field=models.CharField(default='Ramp', max_length=10),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='service_type',
            field=models.CharField(default='Ramp', max_length=10),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='service_type',
            field=models.CharField(default='Ramp', max_length=10),
        ),
    ]
