# Generated by Django 5.2.4 on 2025-09-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0024_rename_door_delivery_service_air_freight_tbl_hazardous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_freight_tbl',
            name='door_delivery_charges',
        ),
        migrations.RemoveField(
            model_name='customs_brokerage_tbl',
            name='door_delivery_charges',
        ),
        migrations.RemoveField(
            model_name='ocean_freight_tbl',
            name='door_delivery_charges',
        ),
        migrations.RemoveField(
            model_name='roro_tbl',
            name='door_delivery_charges',
        ),
    ]
