# Generated by Django 5.2.4 on 2025-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0025_remove_air_freight_tbl_door_delivery_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_freight_tbl',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='customs_brokerage_tbl',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='ocean_freight_tbl',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='roro_tbl',
            name='service_type',
        ),
        migrations.AddField(
            model_name='air_freight_tbl',
            name='tracking',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='customs_brokerage_tbl',
            name='tracking',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='ocean_freight_tbl',
            name='tracking',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='roro_tbl',
            name='tracking',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
