# Generated by Django 5.2.4 on 2025-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0026_remove_air_freight_tbl_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='credits_application_signed_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='gsa_signed_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='loi_signed_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
