# Generated by Django 5.2.4 on 2025-09-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0027_onboarding_credits_application_signed_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='quoting_id',
        ),
        migrations.DeleteModel(
            name='goods',
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
