# Generated by Django 5.2.4 on 2025-09-28 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0028_remove_vehicle_quoting_id_delete_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_freight_tbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('time_received', models.TimeField()),
                ('service_type', models.CharField(max_length=50)),
                ('shipper_export_number', models.TextField(default='N/A', max_length=300)),
                ('receiver_company_name', models.CharField(max_length=100)),
                ('receiver_fullname', models.CharField(max_length=100)),
                ('receiver_phone_number', models.CharField(max_length=30)),
                ('receiver_email', models.CharField(max_length=100)),
                ('receiver_tax_id', models.CharField(default='N/A', max_length=50)),
                ('receiver_driver_lincence_number', models.CharField(default='N/A', max_length=50)),
                ('receiver_passport_no', models.CharField(default='N/A', max_length=50)),
                ('receiver_address', models.TextField(max_length=300)),
                ('desired_type_of_release', models.CharField(max_length=100)),
                ('booking_reference_number', models.CharField(default='N/A', max_length=50)),
                ('container_number', models.CharField(default='N/A', max_length=50)),
                ('vessel_number', models.CharField(default='N/A', max_length=10)),
                ('hs_code', models.CharField(default='N/A', max_length=20)),
                ('cers', models.IntegerField(default=0)),
                ('comments', models.TextField(default='N/A', max_length=300)),
                ('updated_by', models.CharField(default='0', max_length=50)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(default='Pending', max_length=20)),
                ('locked_by', models.CharField(default='0', max_length=50)),
                ('gsa_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_freight_gsa_by_id', to='Login.gsa_agreement_form_tbl')),
                ('quote_request_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_freight_by_id', to='Login.ocean_freight_tbl')),
            ],
            options={
                'db_table': 'booking_freight_tbl',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_quantity', models.IntegerField(default=1)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_value_in_CAD', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booking_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_booking_id_ref', to='Bookings.booking_freight_tbl')),
                ('gsa_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_gsa_by_id', to='Login.gsa_agreement_form_tbl')),
                ('quote_request_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_quote_request_id_ref', to='Login.ocean_freight_tbl', to_field='request_id')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_vin', models.CharField(max_length=100, unique=True)),
                ('vehicle_cost_in_CAD', models.CharField(default='0.00', max_length=10)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('booking_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_booking_id_ref', to='Bookings.booking_freight_tbl')),
                ('gsa_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_gsa_by_id', to='Login.gsa_agreement_form_tbl')),
                ('quote_request_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_quote_request_id_ref', to='Login.ocean_freight_tbl', to_field='request_id')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
