# Generated by Django 5.2.4 on 2025-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_freight_tbl',
            name='quote_reference_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
