# Generated by Django 5.2.4 on 2025-10-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_booking_freight_tbl_quote_reference_number'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_freight_tbl',
            name='quote_request_id_ref',
        ),
        migrations.AddField(
            model_name='booking_freight_tbl',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='booking_freight_tbl',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
