# Generated by Django 5.2.4 on 2025-10-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_remove_booking_freight_tbl_quote_request_id_ref_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='quote_request_id_ref',
        ),
        migrations.AddField(
            model_name='goods',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='goods',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_value_in_CAD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
