# Generated by Django 5.2.4 on 2025-10-13 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_remove_goods_quote_request_id_ref_goods_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='quote_request_id_ref',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_cost_in_CAD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
