# Generated by Django 5.2.4 on 2026-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_remove_vehicle_quote_request_id_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='quote_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='quote_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
