# Generated by Django 5.2.4 on 2026-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_goods_quote_request_vehicle_quote_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_freight_tbl',
            name='blockchain_tx_receipt',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
