# Generated by Django 5.2.4 on 2026-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_alter_booking_freight_tbl_blockchain_tx_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_freight_tbl',
            name='blockchain_tx_receipt',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
