# Generated by Django 5.2.4 on 2026-04-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_alter_booking_freight_tbl_cers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_freight_tbl',
            name='cers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('sequence', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('passed', 'Passed')], default='pending', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='Bookings.booking_freight_tbl')),
            ],
            options={
                'db_table': 'tracking_point',
            },
        ),
    ]
