# Generated by Django 5.2.4 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_alter_booking_freight_tbl_cers_trackingpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpoint',
            name='booking_reference_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingpoint',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrackingPoint_set', to='Bookings.booking_freight_tbl'),
        ),
    ]
